name: ubuntu-bundler3

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  ubuntu_bundler3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.4.10, 2.5.8, 2.6.6, 2.7.1 ]
        rgv: [ v3.1.2, .. ]
    env:
      RGV: ${{ matrix.rgv }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Prepare dependencies
        run: |
          git submodule update -i
          BUNDLER_SPEC_SUB_VERSION=3.0.0 bin/rake override_version
          bin/rake spec:deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
      - name: Run Test with realworld
        run: |
          bin/rake spec:realworld
        env:
          BUNDLER_SPEC_PRE_RECORDED: 1
        working-directory: ./bundler
      - name: Run Test with sudo
        run: |
          bin/rake spec:sudo
        working-directory: ./bundler
    timeout-minutes: 60
